name: 'Validation of PR to Able/Max Develop branch'
on:
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]
    paths:
      - 'src/**'
      - 'src-org-dependent/**'
      - 'devops-scripts/**'
      - '.github/workflows/**'
      - 'data/**'
      - 'config/**'
      - 'src-omni/**'
      - 'runbook/files/**'
      - 'src-temp/**'
    branches:
      - develop
      - develop/*
      - qa/able
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  validate-branch-source:
    name: 'Validate Source Branch for PRs to QA'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      BASE_REF: ${{ github.base_ref }}
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - name: Check if PR source branch is allowed for qa/*
        run: |
          echo "ref: ${{ github.base_ref }}"
          if [[ "$BASE_REF" == qa/* ]]; then
            if [[ "$HEAD_REF" != qa_merge/* && $HEAD_REF != develop && $HEAD_REF != release/* && $HEAD_REF != chore/* ]]; then
              echo "You cannot create PR from ${{ github.head_ref }}, PR will be automatically created after merging the ticket branch into the epic"
              echo "Please review the doc: https://santander-group-uk.atlassian.net/wiki/spaces/SFCOE1/pages/685509930/Multi-Stream+Development+Branching"
              exit 1
            fi  
          fi

  
  see-ref:
    name: 'Ref'
    runs-on: ubuntu-latest
    env:
      REF: ${{ contains(github.ref, 'able') && 'AbleQA' || 'MaxQA' }}
    steps:
      - name: Ref
        run: |
          echo "$REF"
          echo "ref ${{ github.ref }}"
  
  merge_queue:
    name: 'Merge Queue'
    needs: validate-branch-source
    if: always()
    uses: ./.github/workflows/develop-merge-queue-validation.yml
    with:
      environment: ${{ (github.event_name == 'pull_request' && contains(github.base_ref, 'able')) || (github.event_name == 'merge_group' && contains(github.event.pull_request.base.ref, 'able')) && 'AbleQA' || 'MaxQA' }}
      should_deploy_or_validate: ${{ github.event_name == 'pull_request' && 'validate' || 'deploy' }}
    secrets: inherit
